💚 Build app in action

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -10,6 +10,26 @@ jobs:
     steps:
       - run: echo "Starting deployment 🚀"
       - uses: actions/checkout@v3
+        with:
+          ref: 'dev'
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v2.2.4
+        with:
+          version: 7.3
+      - uses: actions/setup-node@v3
+        with:
+          cache: 'pnpm'
+      - name: Install node dependencies
+        run: pnpm i --frozen-lockfile --prod || echo "🛑 Failed to install project"
+        continue-on-error: false
+      - name: Build project
+        run: pnpm build || echo "🛑 Failed to build project"
+        continue-on-error: false
+        env:
+          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
+          PUBLIC_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
+      - uses: actions/checkout@v3
       - uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SSH_KEY }}
